from pythonbinder import __version__, __author__, __telegram__

print("=" * 60)
print(f"PythonBinder v{__version__}")
print(f"Developer: {__author__}")
print(f"Telegram: @{__telegram__}")
print("=" * 60)
print()
print("Library installed successfully!")
print()
print("Usage Examples:")
print("  python py-PythonBinder --main.py")
print("  python py-PythonBinder --app.py --name MyApp")
print("  python py-PythonBinder --gui.py --noconsole --icon logo.png")
print()
print("For help:")
print("  python py-PythonBinder")
print()
print("=" * 60)
print("MERO - The Most Powerful Python to EXE Compiler")
print("=" * 60)
